"""
Mock Jira data for Project Management Agent — State Street Investment Management.
Simulates Jira projects, issues, and team members for SSIM technology and operations.
"""

import datetime

_TODAY = datetime.date.today().isoformat()
_SPRINT_START = (datetime.date.today() - datetime.timedelta(days=3)).isoformat()
_SPRINT_END = (datetime.date.today() + datetime.timedelta(days=11)).isoformat()
_NEXT_SPRINT_END = (datetime.date.today() + datetime.timedelta(days=25)).isoformat()

MOCK_TEAM_MEMBERS = [
    {
        "id": "tm_001",
        "name": "Sarah Chen",
        "email": "sarah.chen@statestreet.com",
        "title": "Senior Software Engineer",
        "team": "Investment Technology",
        "skills": ["Python", "Cloud Infrastructure", "Data Pipelines", "GCP", "Kafka"],
        "projects": ["SSIM-TECH", "SSIM-DATA"],
        "current_sprint_points": 16,
        "availability": "Full",
        "timezone": "America/New_York",
    },
    {
        "id": "tm_002",
        "name": "James Okonkwo",
        "email": "james.okonkwo@statestreet.com",
        "title": "Quantitative Risk Analyst",
        "team": "Risk & Compliance",
        "skills": ["Python", "R", "Risk Modelling", "VaR", "Stress Testing", "Regulatory Reporting"],
        "projects": ["SSIM-RISK", "SSIM-COMPLIANCE"],
        "current_sprint_points": 12,
        "availability": "Full",
        "timezone": "America/New_York",
    },
    {
        "id": "tm_003",
        "name": "Anna Petrov",
        "email": "anna.petrov@statestreet.com",
        "title": "ESG Data Scientist",
        "team": "ESG & Sustainable Investing",
        "skills": ["Python", "ESG Data", "SFDR", "Reporting", "Machine Learning", "Snowflake"],
        "projects": ["SSIM-ESG", "SSIM-DATA"],
        "current_sprint_points": 22,
        "availability": "Limited (80%)",
        "timezone": "America/New_York",
    },
    {
        "id": "tm_004",
        "name": "Mark Johnson",
        "email": "mark.johnson@statestreet.com",
        "title": "Investment Operations Manager",
        "team": "Investment Operations",
        "skills": ["Reconciliation", "Trade Settlement", "Charles River", "SimCorp Dimension", "Project Management"],
        "projects": ["SSIM-OPS", "SSIM-TECH"],
        "current_sprint_points": 8,
        "availability": "Full",
        "timezone": "America/New_York",
    },
    {
        "id": "tm_005",
        "name": "Lisa Huang",
        "email": "lisa.huang@statestreet.com",
        "title": "Platform Engineer",
        "team": "Investment Technology",
        "skills": ["Kubernetes", "Terraform", "GCP", "CI/CD", "Security", "Docker"],
        "projects": ["SSIM-TECH", "SSIM-CLOUD"],
        "current_sprint_points": 28,
        "availability": "Overloaded",
        "timezone": "America/Chicago",
    },
    {
        "id": "tm_006",
        "name": "Robert Kim",
        "email": "robert.kim@statestreet.com",
        "title": "Compliance Technology Lead",
        "team": "Risk & Compliance",
        "skills": ["Regulatory Reporting", "SEC", "MiFID II", "AIFMD", "Python", "SQL"],
        "projects": ["SSIM-COMPLIANCE", "SSIM-RISK"],
        "current_sprint_points": 14,
        "availability": "Full",
        "timezone": "America/New_York",
    },
    {
        "id": "tm_007",
        "name": "Peter Walsh",
        "email": "peter.walsh@statestreet.com",
        "title": "Head of Client Solutions Technology",
        "team": "Client Solutions",
        "skills": ["Product Management", "Client Reporting", "API Design", "Python", "SQL"],
        "projects": ["SSIM-CLIENT", "SSIM-TECH"],
        "current_sprint_points": 6,
        "availability": "Full",
        "timezone": "America/New_York",
    },
    {
        "id": "tm_008",
        "name": "David Chen",
        "email": "david.chen@statestreet.com",
        "title": "Data Engineer",
        "team": "Data Platform",
        "skills": ["Python", "Spark", "BigQuery", "dbt", "Airflow", "Snowflake"],
        "projects": ["SSIM-DATA", "SSIM-ESG"],
        "current_sprint_points": 18,
        "availability": "Full",
        "timezone": "America/New_York",
    },
]

MOCK_JIRA_PROJECTS = [
    {
        "key": "SSIM-TECH",
        "name": "Investment Technology Platform Modernisation",
        "description": "Migration of legacy order management system (OMS) to cloud-native architecture on GCP. Includes real-time trade execution, portfolio analytics, and API modernisation.",
        "lead": "Sarah Chen",
        "status": "In Progress",
        "start_date": "2026-02-01",
        "target_completion": "2026-09-30",
        "sprint": f"Sprint 18 ({_SPRINT_START} – {_SPRINT_END})",
        "team": ["Sarah Chen", "Lisa Huang", "Mark Johnson", "Peter Walsh"],
        "total_issues": 87,
        "open_issues": 34,
        "priority": "High",
        "goals": [
            "Migrate OMS from SimCorp to cloud-native solution",
            "Achieve 99.99% uptime SLA for trading systems",
            "Reduce trade execution latency by 40%",
            "Full API coverage for all investment workflows",
        ],
        "risks": [
            "Lisa Huang overloaded — infra work at risk",
            "Dependency on vendor API v3 (not yet released)",
            "Regulatory sign-off required before go-live",
        ],
    },
    {
        "key": "SSIM-RISK",
        "name": "Risk Analytics Platform Upgrade",
        "description": "Upgrade to next-generation risk analytics: real-time VaR, factor decomposition, liquidity risk, and stress testing. Integrate with new cloud OMS.",
        "lead": "James Okonkwo",
        "status": "On Track",
        "start_date": "2026-01-15",
        "target_completion": "2026-07-31",
        "sprint": f"Sprint 14 ({_SPRINT_START} – {_SPRINT_END})",
        "team": ["James Okonkwo", "Robert Kim"],
        "total_issues": 52,
        "open_issues": 18,
        "priority": "High",
        "goals": [
            "Real-time VaR calculation across all mandates",
            "Factor exposure reporting for active strategies",
            "Stress test automation (market crash, rate shock scenarios)",
            "Integration with SSIM-TECH OMS",
        ],
        "risks": [
            "Integration with new OMS creates timing dependency on SSIM-TECH",
            "Regulatory deadline: AIFMD stress test reporting June 30",
        ],
    },
    {
        "key": "SSIM-ESG",
        "name": "ESG Data & Analytics Platform",
        "description": "Build SSIM's internal ESG data platform: aggregate ESG scores from MSCI, Sustainalytics, Bloomberg; automate SFDR reporting; build carbon footprint analytics.",
        "lead": "Anna Petrov",
        "status": "At Risk",
        "start_date": "2026-03-01",
        "target_completion": "2026-08-31",
        "sprint": f"Sprint 10 ({_SPRINT_START} – {_SPRINT_END})",
        "team": ["Anna Petrov", "David Chen"],
        "total_issues": 41,
        "open_issues": 22,
        "priority": "High",
        "goals": [
            "Unified ESG data pipeline from 3 vendors",
            "SFDR Article 8/9 automated reporting",
            "Carbon footprint calculator for all strategies",
            "Real-time ESG score dashboard for PMs",
        ],
        "risks": [
            "Anna Petrov overloaded — sprint velocity at risk",
            "Sustainalytics data feed delayed (vendor side)",
            "SFDR Q2 reporting deadline: July 31 — critical path",
        ],
    },
    {
        "key": "SSIM-OPS",
        "name": "Investment Operations Automation",
        "description": "Automate reconciliation, trade settlement confirmation, and client reporting. Reduce manual processes by 70%.",
        "lead": "Mark Johnson",
        "status": "On Track",
        "start_date": "2026-04-01",
        "target_completion": "2026-10-31",
        "sprint": f"Sprint 6 ({_SPRINT_START} – {_SPRINT_END})",
        "team": ["Mark Johnson", "David Chen"],
        "total_issues": 38,
        "open_issues": 14,
        "priority": "Medium",
        "goals": [
            "Automated T+1 reconciliation across all custodians",
            "Straight-through processing (STP) for domestic equity trades",
            "Automated client performance report generation",
            "Exception management dashboard",
        ],
        "risks": [
            "Custodian API access (State Street Global Services) still in approval",
        ],
    },
    {
        "key": "SSIM-COMPLIANCE",
        "name": "Regulatory Compliance Technology",
        "description": "Automate SEC Marketing Rule compliance checks, MiFID II transaction reporting, and AIFMD/UCITS regulatory filings.",
        "lead": "Robert Kim",
        "status": "On Track",
        "start_date": "2026-02-15",
        "target_completion": "2026-06-30",
        "sprint": f"Sprint 12 ({_SPRINT_START} – {_SPRINT_END})",
        "team": ["Robert Kim", "James Okonkwo"],
        "total_issues": 29,
        "open_issues": 9,
        "priority": "Critical",
        "goals": [
            "SEC Marketing Rule automated composite validation",
            "MiFID II real-time transaction reporting",
            "AIFMD stress test automation",
            "UCITS compliance monitoring",
        ],
        "risks": [
            "AIFMD reporting deadline: June 30 — 4 weeks away, 2 stories still in backlog",
        ],
    },
]

MOCK_JIRA_ISSUES = [
    # ── SSIM-TECH Issues ─────────────────────────────────────────────────────
    {
        "key": "SSIM-TECH-101",
        "project_key": "SSIM-TECH",
        "summary": "Migrate OMS order blotter to GCP Cloud Run",
        "status": "In Progress",
        "issue_type": "Epic",
        "priority": "Critical",
        "assignee": "Sarah Chen",
        "story_points": 0,
        "due_date": "2026-07-31",
        "epic": None,
        "description": "Migrate the core order blotter from on-premise to GCP Cloud Run. Includes containerisation, authentication, and load testing.",
    },
    {
        "key": "SSIM-TECH-102",
        "project_key": "SSIM-TECH",
        "summary": "Containerise OMS order entry service (Docker)",
        "status": "In Progress",
        "issue_type": "Story",
        "priority": "Critical",
        "assignee": "Sarah Chen",
        "story_points": 8,
        "due_date": "2026-05-23",
        "epic": "SSIM-TECH-101",
        "description": "Containerise the order entry service. Dockerfile complete; failing on auth integration test.",
    },
    {
        "key": "SSIM-TECH-103",
        "project_key": "SSIM-TECH",
        "summary": "Deploy Kubernetes cluster for trading services on GCP",
        "status": "Blocked",
        "issue_type": "Story",
        "priority": "Critical",
        "assignee": "Lisa Huang",
        "story_points": 13,
        "due_date": "2026-05-20",
        "epic": "SSIM-TECH-101",
        "description": "Blocked waiting for GCP project quota increase request (ticket #GCP-4492). Submitted 2 weeks ago. Lisa escalated to GCP TAM.",
    },
    {
        "key": "SSIM-TECH-104",
        "project_key": "SSIM-TECH",
        "summary": "Design REST API v2 for portfolio analytics service",
        "status": "In Progress",
        "issue_type": "Story",
        "priority": "High",
        "assignee": "Peter Walsh",
        "story_points": 5,
        "due_date": "2026-05-30",
        "epic": None,
        "description": "OpenAPI spec 80% complete. Pending review from risk team on data model.",
    },
    {
        "key": "SSIM-TECH-105",
        "project_key": "SSIM-TECH",
        "summary": "Implement Terraform IaC for trading infrastructure",
        "status": "In Progress",
        "issue_type": "Story",
        "priority": "High",
        "assignee": "Lisa Huang",
        "story_points": 8,
        "due_date": "2026-05-27",
        "epic": None,
        "description": "Terraform modules for Cloud SQL, Pub/Sub, and VPC networking. 60% complete.",
    },
    {
        "key": "SSIM-TECH-106",
        "project_key": "SSIM-TECH",
        "summary": "Performance testing: trade execution latency benchmarks",
        "status": "To Do",
        "issue_type": "Task",
        "priority": "High",
        "assignee": "Sarah Chen",
        "story_points": 5,
        "due_date": "2026-06-06",
        "epic": "SSIM-TECH-101",
        "description": "Design and run load tests targeting <50ms execution latency. Compare to baseline 87ms.",
    },
    {
        "key": "SSIM-TECH-107",
        "project_key": "SSIM-TECH",
        "summary": "Vendor API v3 integration — awaiting vendor release",
        "status": "Blocked",
        "issue_type": "Story",
        "priority": "Medium",
        "assignee": "Mark Johnson",
        "story_points": 8,
        "due_date": "2026-06-30",
        "epic": None,
        "description": "Blocked: vendor API v3 not yet released. Expected late June. Mark tracking with vendor PM.",
    },
    {
        "key": "SSIM-TECH-108",
        "project_key": "SSIM-TECH",
        "summary": "Security review and pen test of new trading endpoints",
        "status": "To Do",
        "issue_type": "Task",
        "priority": "High",
        "assignee": "Lisa Huang",
        "story_points": 5,
        "due_date": "2026-06-15",
        "epic": None,
        "description": "Schedule penetration test with InfoSec. Required before go-live sign-off.",
    },
    {
        "key": "SSIM-TECH-109",
        "project_key": "SSIM-TECH",
        "summary": "CI/CD pipeline for trading services (Cloud Build)",
        "status": "Done",
        "issue_type": "Story",
        "priority": "High",
        "assignee": "Lisa Huang",
        "story_points": 5,
        "due_date": "2026-05-10",
        "epic": None,
        "description": "Completed. Cloud Build pipeline with automated tests and staging deployment.",
    },
    # ── SSIM-RISK Issues ──────────────────────────────────────────────────────
    {
        "key": "SSIM-RISK-201",
        "project_key": "SSIM-RISK",
        "summary": "Implement real-time VaR calculation engine (Python/C++)",
        "status": "In Progress",
        "issue_type": "Epic",
        "priority": "Critical",
        "assignee": "James Okonkwo",
        "story_points": 0,
        "due_date": "2026-06-30",
        "epic": None,
        "description": "Real-time parametric and historical VaR across all mandates. Target: <5 second refresh.",
    },
    {
        "key": "SSIM-RISK-202",
        "project_key": "SSIM-RISK",
        "summary": "Factor decomposition API — active equity strategies",
        "status": "In Progress",
        "issue_type": "Story",
        "priority": "High",
        "assignee": "James Okonkwo",
        "story_points": 8,
        "due_date": "2026-05-28",
        "epic": "SSIM-RISK-201",
        "description": "Barra-compatible factor attribution API. 70% complete, integrating with OMS data feed.",
    },
    {
        "key": "SSIM-RISK-203",
        "project_key": "SSIM-RISK",
        "summary": "AIFMD stress test automation — CRITICAL regulatory deadline",
        "status": "In Progress",
        "issue_type": "Story",
        "priority": "Critical",
        "assignee": "Robert Kim",
        "story_points": 8,
        "due_date": "2026-06-20",
        "epic": None,
        "description": "Automate AIFMD stress test scenarios (liquidity, market, counterparty). Deadline June 30 regulatory filing.",
    },
    {
        "key": "SSIM-RISK-204",
        "project_key": "SSIM-RISK",
        "summary": "Liquidity risk monitoring dashboard",
        "status": "To Do",
        "issue_type": "Story",
        "priority": "Medium",
        "assignee": "James Okonkwo",
        "story_points": 5,
        "due_date": "2026-06-30",
        "epic": None,
        "description": "Dashboard showing bid-ask spread, market depth, and redemption stress metrics for all funds.",
    },
    {
        "key": "SSIM-RISK-205",
        "project_key": "SSIM-RISK",
        "summary": "Integrate risk engine with new cloud OMS (SSIM-TECH dependency)",
        "status": "Blocked",
        "issue_type": "Story",
        "priority": "High",
        "assignee": "James Okonkwo",
        "story_points": 5,
        "due_date": "2026-07-15",
        "epic": None,
        "description": "Blocked: depends on SSIM-TECH-101 OMS migration completion. ETA: late July.",
    },
    # ── SSIM-ESG Issues ───────────────────────────────────────────────────────
    {
        "key": "SSIM-ESG-301",
        "project_key": "SSIM-ESG",
        "summary": "Unified ESG data pipeline — MSCI + Sustainalytics + Bloomberg",
        "status": "In Progress",
        "issue_type": "Epic",
        "priority": "High",
        "assignee": "Anna Petrov",
        "story_points": 0,
        "due_date": "2026-07-31",
        "epic": None,
        "description": "Ingest, normalise, and store ESG scores from 3 data vendors into SSIM data lake.",
    },
    {
        "key": "SSIM-ESG-302",
        "project_key": "SSIM-ESG",
        "summary": "MSCI ESG data ingestion pipeline (Airflow DAG)",
        "status": "In Progress",
        "issue_type": "Story",
        "priority": "High",
        "assignee": "David Chen",
        "story_points": 8,
        "due_date": "2026-05-25",
        "epic": "SSIM-ESG-301",
        "description": "Airflow DAG for daily MSCI ESG data ingestion into BigQuery. 90% complete, in UAT.",
    },
    {
        "key": "SSIM-ESG-303",
        "project_key": "SSIM-ESG",
        "summary": "Sustainalytics data feed — blocked by vendor delay",
        "status": "Blocked",
        "issue_type": "Story",
        "priority": "High",
        "assignee": "David Chen",
        "story_points": 5,
        "due_date": "2026-05-31",
        "epic": "SSIM-ESG-301",
        "description": "Blocked: Sustainalytics API credentials delayed on vendor side. Escalated to account manager.",
    },
    {
        "key": "SSIM-ESG-304",
        "project_key": "SSIM-ESG",
        "summary": "SFDR Article 8/9 automated reporting module",
        "status": "In Progress",
        "issue_type": "Story",
        "priority": "Critical",
        "assignee": "Anna Petrov",
        "story_points": 13,
        "due_date": "2026-06-30",
        "epic": None,
        "description": "Automated generation of SFDR periodic reports. Critical path for July 31 regulatory deadline.",
    },
    {
        "key": "SSIM-ESG-305",
        "project_key": "SSIM-ESG",
        "summary": "Carbon footprint calculator — portfolio and fund level",
        "status": "To Do",
        "issue_type": "Story",
        "priority": "High",
        "assignee": "Anna Petrov",
        "story_points": 8,
        "due_date": "2026-07-15",
        "epic": None,
        "description": "Calculate WACI (Weighted Average Carbon Intensity) at portfolio and fund level. Feeds GIC pitch materials.",
    },
    {
        "key": "SSIM-ESG-306",
        "project_key": "SSIM-ESG",
        "summary": "ESG analytics dashboard — PM-facing real-time view",
        "status": "To Do",
        "issue_type": "Story",
        "priority": "Medium",
        "assignee": "Unassigned",
        "story_points": 8,
        "due_date": "2026-08-15",
        "epic": None,
        "description": "Portfolio manager dashboard: ESG scores, factor exposures, proxy voting status per holding.",
    },
    # ── SSIM-COMPLIANCE Issues ────────────────────────────────────────────────
    {
        "key": "SSIM-COMP-401",
        "project_key": "SSIM-COMPLIANCE",
        "summary": "SEC Marketing Rule — automated composite validation",
        "status": "In Progress",
        "issue_type": "Story",
        "priority": "Critical",
        "assignee": "Robert Kim",
        "story_points": 8,
        "due_date": "2026-05-30",
        "epic": None,
        "description": "Validates composite performance presentations against SEC Marketing Rule requirements before external distribution.",
    },
    {
        "key": "SSIM-COMP-402",
        "project_key": "SSIM-COMPLIANCE",
        "summary": "MiFID II transaction reporting automation",
        "status": "Done",
        "issue_type": "Story",
        "priority": "High",
        "assignee": "Robert Kim",
        "story_points": 8,
        "due_date": "2026-04-30",
        "epic": None,
        "description": "Completed. Real-time MiFID II reporting to ARM. All T+1 reports transmitted successfully.",
    },
    {
        "key": "SSIM-COMP-403",
        "project_key": "SSIM-COMPLIANCE",
        "summary": "AIFMD periodic reporting — Q2 2026 preparation",
        "status": "To Do",
        "issue_type": "Task",
        "priority": "Critical",
        "assignee": "James Okonkwo",
        "story_points": 5,
        "due_date": "2026-06-25",
        "epic": None,
        "description": "Prepare Q2 2026 AIFMD Annex IV reporting. Deadline June 30. Requires stress test data from SSIM-RISK-203.",
    },
    # ── SSIM-OPS Issues ───────────────────────────────────────────────────────
    {
        "key": "SSIM-OPS-501",
        "project_key": "SSIM-OPS",
        "summary": "Automated T+1 reconciliation — US equity custodians",
        "status": "In Progress",
        "issue_type": "Story",
        "priority": "High",
        "assignee": "Mark Johnson",
        "story_points": 8,
        "due_date": "2026-06-15",
        "epic": None,
        "description": "STP reconciliation for US equity trades with 4 custodians. 60% complete. State Street Global Services API access pending.",
    },
    {
        "key": "SSIM-OPS-502",
        "project_key": "SSIM-OPS",
        "summary": "Client performance report automation (PDF generation)",
        "status": "In Progress",
        "issue_type": "Story",
        "priority": "Medium",
        "assignee": "David Chen",
        "story_points": 8,
        "due_date": "2026-06-30",
        "epic": None,
        "description": "Automated quarterly performance reports for top 50 clients. Template complete; data pipeline in progress.",
    },
    {
        "key": "SSIM-OPS-503",
        "project_key": "SSIM-OPS",
        "summary": "Exception management dashboard for ops team",
        "status": "To Do",
        "issue_type": "Story",
        "priority": "Low",
        "assignee": "Unassigned",
        "story_points": 5,
        "due_date": "2026-07-31",
        "epic": None,
        "description": "Dashboard for operations team showing open reconciliation breaks and settlement fails.",
    },
]
