"""
Mock data for Sales Support Agent — State Street Investment Management.
Simulates CRM, product library, customer profiles, and Drive documents.
"""

import datetime

_TODAY = datetime.date.today().isoformat()


MOCK_CUSTOMER_PROFILES = [
    {
        "name": "CalPERS",
        "full_name": "California Public Employees' Retirement System",
        "keywords": ["calpers", "california"],
        "type": "Public Pension Fund",
        "country": "United States",
        "total_aum": "$490 billion",
        "key_contacts": [
            {"name": "Michael Torres", "title": "Director of External Management",
             "email": "michael.torres@calpers.ca.gov", "role": "Decision maker"},
            {"name": "Jennifer Wu", "title": "Portfolio Analyst",
             "email": "jennifer.wu@calpers.ca.gov", "role": "Day-to-day contact"},
        ],
        "ssim_relationship": {
            "status": "Active Client",
            "since": "March 2018",
            "ssim_aum": "$8.24 billion",
            "strategies": [
                "Global Equity Passive — MSCI World ex-Tobacco ($7.1B)",
                "US Large Cap Index — S&P 500 ($1.14B)",
            ],
            "relationship_manager": "Sarah Chen (SSIM Boston)",
            "mandate_expiry": "December 31, 2026",
            "annual_revenue": "$1.2M",
        },
        "investment_profile": {
            "return_objective": "7.0% actuarial return assumption",
            "esg_requirements": "Mandatory: tobacco exclusion, weapons screening, climate action. Proxy voting engagement required.",
            "risk_tolerance": "Long-term; accepts short-term volatility for return objectives",
            "investment_committee_frequency": "Quarterly",
        },
        "opportunities": [
            "Mandate renewal Q3 2026 — at risk of competitive review",
            "EM allocation: Michael Torres mentioned interest in $500M EM expansion",
            "Cash management: no SSIM cash product — cross-sell opportunity (~$300M)",
            "Securities lending income negotiation — fee review due",
        ],
        "risks": [
            "Fee pressure: CalPERS benchmarking fees vs Vanguard (1.0 bps)",
            "ESG compliance: new climate exclusion list arriving — implementation timeline risk",
            "New board member pushing for passive-to-active rotation review",
        ],
        "last_review": f"Q2 2026 review — {_TODAY}",
    },
    {
        "name": "Ontario Teachers' Pension Plan",
        "full_name": "Ontario Teachers' Pension Plan Board (OTPP)",
        "keywords": ["otpp", "ontario", "teachers"],
        "type": "Canadian Public Pension Fund",
        "country": "Canada",
        "total_aum": "CAD $255 billion",
        "key_contacts": [
            {"name": "David Morrison", "title": "Head of External Managers",
             "email": "david.morrison@otpp.com", "role": "Decision maker"},
            {"name": "Francesca Lim", "title": "Senior Investment Analyst",
             "email": "francesca.lim@otpp.com", "role": "Evaluator"},
            {"name": "Priya Mehta", "title": "Chief Investment Officer",
             "email": "priya.mehta@otpp.com", "role": "Final approver"},
        ],
        "ssim_relationship": {
            "status": "Prospect — RFP Finalist",
            "since": "N/A",
            "ssim_aum": "$0 (not yet a client)",
            "strategies": ["Shortlisted for $2B Active Quantitative Equity mandate"],
            "relationship_manager": "Peter Walsh (SSIM Boston)",
            "mandate_expiry": "N/A",
            "annual_revenue_potential": "$4M (at 20 bps on $2B)",
        },
        "investment_profile": {
            "return_objective": "Real return of 4% above CPI",
            "esg_requirements": "Net Zero by 2050. TCFD aligned. Climate risk integration required.",
            "existing_active_managers": ["Acadian Asset Management", "Two Sigma Investments"],
            "key_decision_factors": [
                "Low correlation to existing managers (Acadian, Two Sigma)",
                "Drawdown protection in stress scenarios",
                "Factor transparency and explainability",
                "Competitive fee structure",
                "Team stability (key person risk)",
            ],
        },
        "opportunities": [
            "Win $2B Active Quant Equity mandate (final pitch today)",
            "Future: Passive equity ($500M potential if active wins)",
            "ESG overlay: OTPP committed to net zero — SSIM ESG integration a differentiator",
        ],
        "risks": [
            "Competition: Two Sigma, Acadian (both incumbents), AQR on shortlist",
            "CIO Priya Mehta joining unexpectedly — must lead with risk management story",
            "Correlation concern: SSIM quant factors may overlap with Acadian",
        ],
        "last_review": "Final pitch presentation — today",
    },
    {
        "name": "GIC",
        "full_name": "GIC Private Limited (Government of Singapore Investment Corporation)",
        "keywords": ["gic", "singapore"],
        "type": "Sovereign Wealth Fund",
        "country": "Singapore",
        "total_aum": ">$770 billion (estimated)",
        "key_contacts": [
            {"name": "Wei Chen", "title": "Senior Investment Manager",
             "email": "wei.chen@gic.com.sg", "role": "Initial contact"},
        ],
        "ssim_relationship": {
            "status": "Prospect — Early Stage",
            "since": "N/A",
            "ssim_aum": "$0",
            "strategies": ["Exploring $5B ESG Global Equity mandate"],
            "relationship_manager": "Dev (SSIM — initial outreach)",
            "annual_revenue_potential": "$3M (at 6 bps on $5B)",
        },
        "investment_profile": {
            "return_objective": "Long-term real returns above global inflation",
            "esg_requirements": "Strong: SFDR Article 8 minimum, Article 9 preferred. Carbon footprint data required. TCFD compliant.",
            "key_decision_factors": [
                "ESG credibility and policy depth",
                "SFDR compliance documentation",
                "Carbon reduction vs benchmark",
                "Proxy voting record on climate",
                "Securities lending programme (SWFs often value this)",
            ],
        },
        "opportunities": [
            "$5B ESG Global Equity mandate — high probability if we demonstrate ESG leadership",
            "Potentially expand to ESG Fixed Income ($1-2B) if equity mandate won",
            "Securities lending: large mandate generates $5-8M annual lending income for GIC",
        ],
        "risks": [
            "BlackRock has existing GIC relationship (iShares Sustainability range)",
            "GIC may require Singapore regulatory structure (not just UCITS)",
            "Early stage — no timeline defined yet",
        ],
        "last_review": "Initial scoping call — tomorrow",
    },
    {
        "name": "Abu Dhabi Investment Authority",
        "full_name": "Abu Dhabi Investment Authority (ADIA)",
        "keywords": ["adia", "abu dhabi"],
        "type": "Sovereign Wealth Fund",
        "country": "UAE",
        "total_aum": "$993 billion (estimated)",
        "key_contacts": [
            {"name": "Khalid Al-Falah", "title": "Head of Indexed Strategies",
             "email": "k.alfalah@adia.ae", "role": "PM contact"},
        ],
        "ssim_relationship": {
            "status": "Active Client",
            "since": "January 2014",
            "ssim_aum": "$12.5 billion",
            "strategies": [
                "Global Equity Index — MSCI ACWI ($9.2B)",
                "US Fixed Income Index ($2.1B)",
                "Cash Management ($1.2B)",
            ],
            "relationship_manager": "Peter Walsh (SSIM London)",
            "annual_revenue": "$2.1M",
        },
        "opportunities": [
            "EM Equity Index: ADIA reviewing EM allocation — potential $2-3B mandate",
            "ESG: ADIA signatory to UNPRI — explore ESG overlay on existing equity mandate",
            "Active Quant: ADIA beginning evaluation of active managers",
        ],
        "risks": [
            "Long-standing relationship: complacency risk on service quality",
            "Vanguard pitching EM Index — fee competition expected",
        ],
    },
    {
        "name": "New York State Common Retirement Fund",
        "full_name": "New York State Common Retirement Fund",
        "keywords": ["nyscrf", "new york state", "new york common"],
        "type": "Public Pension Fund",
        "country": "United States",
        "total_aum": "$265 billion",
        "key_contacts": [
            {"name": "Thomas Bradley", "title": "Deputy Comptroller for Asset Management",
             "email": "tbradley@osc.ny.gov", "role": "Senior decision maker"},
        ],
        "ssim_relationship": {
            "status": "Prospect — Re-engagement",
            "since": "Lost mandate 2022",
            "ssim_aum": "$0 (mandate lost to Vanguard on fees)",
            "strategies": ["Re-pitching for $1.5B Global Equity Index"],
            "relationship_manager": "Sarah Chen (SSIM Boston)",
        },
        "opportunities": [
            "Global Equity Index re-pitch ($1.5B) — NYSCRF reviewing Vanguard performance",
            "Vanguard doesn't offer securities lending income — SSIM differentiator",
        ],
        "risks": [
            "Lost mandate 2022 — fee was the reason; must demonstrate superior value (lending income + ESG)",
            "NYSCRF has strong relationships with Vanguard institutional team",
        ],
    },
]

MOCK_PRODUCTS = [
    {
        "name": "SSIM Global Equity Index",
        "type": "Passive Equity",
        "aum": "$890 billion",
        "benchmark": "MSCI World / MSCI ACWI / S&P 500 (client choice)",
        "tags": ["global equity", "index", "passive", "msci world", "acwi", "large cap"],
        "key_facts": {
            "tracking_error_bps": "2-4 bps",
            "fee_range_bps": "0.8-2.5 bps (scale-based)",
            "securities_lending_income_bps": "+8-12 bps",
            "vehicles": ["SMA", "Commingled Fund", "UCITS", "ETF"],
            "esg_options": "Screened, enhanced ESG, custom exclusion lists",
            "inception": "January 2002",
            "10y_active_return_net": "+0.2% (from lending income)",
        },
        "differentiators": [
            "Lowest tracking error in class (2-3 bps)",
            "State Street securities lending adds 8-12 bps net income",
            "Full physical replication (not sampling) for MSCI World",
            "Same-day corporate action processing",
        ],
    },
    {
        "name": "SSIM Active Quantitative Equity",
        "type": "Active Equity",
        "aum": "$48.2 billion",
        "benchmark": "MSCI World",
        "tags": ["active", "quantitative", "equity", "factor", "systematic", "quant", "alpha"],
        "key_facts": {
            "target_alpha_bps_gross": "150-250 bps",
            "tracking_error_range": "1.5-3.0%",
            "information_ratio_5y": 0.90,
            "max_drawdown_2022": "-18.4% vs benchmark -20.1%",
            "fee_bps": "15-25 bps (scale-based)",
            "minimum_investment": "$200M",
            "vehicles": ["SMA", "UCITS", "Cayman Fund"],
            "inception": "January 2008",
        },
        "differentiators": [
            "5-year live IR of 0.90 — top quartile globally",
            "Outperformed in 2022 drawdown (captured only 91% of downside)",
            "Low correlation to Acadian and AQR (alternative factor construction)",
            "Transparent factor exposure reporting (daily)",
        ],
    },
    {
        "name": "SSIM ESG Global Equity",
        "type": "ESG Equity",
        "aum": "$78 billion",
        "benchmark": "MSCI World",
        "tags": ["esg", "sustainable", "equity", "article9", "sfdr", "climate", "net zero",
                 "responsible investment", "green"],
        "key_facts": {
            "sfdr_classification": "Article 9",
            "carbon_reduction_vs_benchmark_pct": "-39%",
            "esg_score_improvement_vs_benchmark": "+22%",
            "fee_bps": "6-12 bps (scale-based)",
            "vehicles": ["SMA", "UCITS (Article 9)"],
            "proxy_voting_climate_support_pct": "89%",
            "paris_alignment": "1.5°C pathway by 2040",
        },
        "differentiators": [
            "SFDR Article 9 — highest EU sustainable classification",
            "39% carbon footprint reduction vs MSCI World benchmark",
            "SSIM Net Zero Asset Managers signatory",
            "Best-in-class proxy voting on climate (89% support rate)",
            "Custom ESG screens available (tobacco, weapons, fossil fuels, gambling)",
        ],
    },
    {
        "name": "SSIM Emerging Markets Equity Index",
        "type": "Passive Equity",
        "aum": "$62 billion",
        "benchmark": "MSCI Emerging Markets",
        "tags": ["emerging markets", "em", "index", "passive", "msci em", "equity"],
        "key_facts": {
            "tracking_error_bps": "15-25 bps",
            "fee_bps": "4-8 bps",
            "securities_lending_income_bps": "+15-25 bps (EM premium)",
            "vehicles": ["SMA", "Commingled Fund", "UCITS"],
        },
        "differentiators": [
            "High securities lending income in EM (15-25 bps)",
            "Deep operational capability in 27 EM markets",
            "Experienced EM trading desk (150+ trader years in EM)",
            "ESG screening available across all EM markets",
        ],
    },
    {
        "name": "SSIM Global Aggregate Bond Index",
        "type": "Passive Fixed Income",
        "aum": "$180 billion",
        "benchmark": "Bloomberg Global Aggregate",
        "tags": ["fixed income", "bond", "aggregate", "passive", "global agg", "index"],
        "key_facts": {
            "tracking_error_bps": "2-4 bps",
            "fee_bps": "2.5-3.5 bps",
            "vehicles": ["SMA", "UCITS", "Commingled Fund"],
            "esg_options": "ESG screened Bloomberg Global Aggregate available",
        },
        "differentiators": [
            "Scale: largest global aggregate manager at $180B AUM",
            "ESG overlay available (corporate bond exclusions)",
            "Green bond identification and tilt option",
        ],
    },
    {
        "name": "SSIM Cash Management",
        "type": "Cash & Short Duration",
        "aum": "$310 billion",
        "benchmark": "Fed Funds / LIBOR replacement",
        "tags": ["cash", "liquidity", "money market", "short duration", "cash management"],
        "key_facts": {
            "prime_liquidity_7d_yield": "5.21%",
            "government_mmf_7d_yield": "5.08%",
            "enhanced_cash_30d_yield": "5.45%",
            "fee_bps": "3.5-7 bps",
            "aaa_rated": True,
        },
        "differentiators": [
            "Backed by State Street's global custody infrastructure",
            "AAA rated by Moody's and S&P",
            "Seamless integration with SSIM equity/fixed income mandates",
            "No separate account minimum (same-day redemption)",
        ],
    },
]

MOCK_CRM_INTERACTIONS = [
    # CalPERS
    {
        "customer": "CalPERS",
        "date": (datetime.date.today() - datetime.timedelta(days=90)).isoformat(),
        "type": "Quarterly Review",
        "participants": ["Michael Torres (CalPERS)", "Sarah Chen (SSIM)", "James Okonkwo (SSIM)"],
        "summary": "Q1 2026 review. Performance +12 bps net of fees. ESG screen compliance confirmed. Fee discussion deferred to mandate renewal in Q3.",
        "outcome": "Positive. Client satisfied with performance. Asked to see EM strategy materials.",
        "next_steps": "Send EM equity fact sheet. Prepare fee proposal for renewal.",
    },
    {
        "customer": "CalPERS",
        "date": (datetime.date.today() - datetime.timedelta(days=180)).isoformat(),
        "type": "Mandate Renewal Discussion",
        "participants": ["Michael Torres (CalPERS)", "Jennifer Wu (CalPERS)", "Sarah Chen (SSIM)", "Peter Walsh (SSIM)"],
        "summary": "Q4 2025 renewal pre-discussion. CalPERS benchmarking fees. Vanguard offering 1.0 bps. SSIM at 1.2 bps. Client values lending income (net +11 bps) and ESG capability.",
        "outcome": "Decision deferred to Q3 2026. SSIM to prepare value-add analysis including lending income net effect.",
        "next_steps": "Prepare lending income analysis. Show net total cost vs Vanguard.",
    },
    {
        "customer": "CalPERS",
        "date": (datetime.date.today() - datetime.timedelta(days=365)).isoformat(),
        "type": "ESG Policy Briefing",
        "participants": ["Jennifer Wu (CalPERS)", "Anna Petrov (SSIM)"],
        "summary": "CalPERS introduced new climate investment policy. Requires managers to demonstrate Paris-alignment. SSIM provided TCFD and carbon footprint analysis.",
        "outcome": "CalPERS satisfied with SSIM ESG approach. ESG reporting to be expanded.",
        "next_steps": "Implement quarterly carbon footprint reporting for CalPERS.",
    },
    # Ontario Teachers
    {
        "customer": "Ontario Teachers' Pension Plan",
        "date": (datetime.date.today() - datetime.timedelta(days=60)).isoformat(),
        "type": "RFP Submission",
        "participants": ["David Morrison (OTPP)", "Peter Walsh (SSIM)", "Dr. Katherine Morris (SSIM CIO)"],
        "summary": "Submitted Active Quant Equity RFP response. Highlighted 5Y IR of 0.90, 2022 drawdown outperformance, and low correlation to Acadian.",
        "outcome": "Shortlisted (top 4 of 12 respondents). Final presentation scheduled.",
        "next_steps": "Final pitch today. Lead with risk management story. CIO Priya Mehta joining.",
    },
    {
        "customer": "Ontario Teachers' Pension Plan",
        "date": (datetime.date.today() - datetime.timedelta(days=21)).isoformat(),
        "type": "RFP Shortlist Notification",
        "participants": ["David Morrison (OTPP)", "Francesca Lim (OTPP)", "Peter Walsh (SSIM)"],
        "summary": "OTPP confirmed SSIM shortlisted. 4 finalists: SSIM, AQR, Two Sigma, Acadian (defending incumbent).",
        "outcome": "Shortlisted. Final presentations: all 4 managers presenting this week.",
        "next_steps": "Prepare for Priya Mehta (CIO) questions on governance and risk management.",
    },
    # GIC
    {
        "customer": "GIC",
        "date": (datetime.date.today() - datetime.timedelta(days=14)).isoformat(),
        "type": "Initial Outreach",
        "participants": ["Wei Chen (GIC)", "Dev (SSIM)"],
        "summary": "GIC reached out following SSIM's ESG leadership recognition at PRI in Person conference. Interest in ESG Global Equity strategy.",
        "outcome": "Scoping call scheduled for tomorrow.",
        "next_steps": "Prepare ESG materials: policy, proxy record, SFDR list, carbon footprint.",
    },
    # NYSCRF
    {
        "customer": "New York State Common Retirement Fund",
        "date": (datetime.date.today() - datetime.timedelta(days=30)).isoformat(),
        "type": "Re-engagement Call",
        "participants": ["Thomas Bradley (NYSCRF)", "Sarah Chen (SSIM)"],
        "summary": "Re-engagement after 2022 mandate loss. NYSCRF unhappy with Vanguard's lack of ESG engagement and securities lending programme. Open to evaluating SSIM again.",
        "outcome": "NYSCRF requested materials on lending income analysis and ESG programme.",
        "next_steps": "Send lending income comparison (SSIM +11 bps vs Vanguard ~0 bps on lending). Arrange full presentation.",
    },
    {
        "customer": "New York State Common Retirement Fund",
        "date": "2022-03-15",
        "type": "Lost Mandate — Fee Review",
        "participants": ["Thomas Bradley (NYSCRF)", "Sarah Chen (SSIM)", "Peter Walsh (SSIM)"],
        "summary": "NYSCRF moved $1.5B Global Equity Index mandate to Vanguard. Reason: fee (Vanguard offered 0.9 bps vs SSIM 1.3 bps). ESG engagement and lending income not weighted in decision.",
        "outcome": "Mandate lost. SSIM relationship maintained at senior level.",
        "next_steps": "Revisit when NYSCRF ESG requirements evolve or fee comparison shifts.",
    },
]

MOCK_EMAILS = [
    {
        "id": "e_s001",
        "from": "michael.torres@calpers.ca.gov",
        "to": "sarah.chen@statestreet.com",
        "subject": "Re: CalPERS Fee Review — Vanguard Proposal Received",
        "date": (datetime.date.today() - datetime.timedelta(days=7)).isoformat() + "T10:00:00-04:00",
        "snippet": "We've received a competitive proposal from Vanguard at 1.0 bps for the global equity mandate. We value the SSIM relationship but need to understand the total cost comparison. Can you put together a net-of-lending analysis?",
        "to_domain": "statestreet.com",
        "customer": "CalPERS",
    },
    {
        "id": "e_s002",
        "from": "francesca.lim@otpp.com",
        "to": "peter.walsh@statestreet.com",
        "subject": "OTPP Active Quant RFP — Evaluation Criteria Update",
        "date": (datetime.date.today() - datetime.timedelta(days=14)).isoformat() + "T14:00:00-04:00",
        "snippet": "Updated weighting: drawdown performance (2022) 30%, information ratio 25%, team stability 20%, fees 15%, ESG integration 10%. CIO particularly focused on downside protection.",
        "customer": "Ontario Teachers' Pension Plan",
    },
    {
        "id": "e_s003",
        "from": "wei.chen@gic.com.sg",
        "to": "dev@chenkeamonwang.altostrat.com",
        "subject": "GIC ESG Investment — Pre-call Materials Request",
        "date": (datetime.date.today() - datetime.timedelta(days=1)).isoformat() + "T03:00:00-04:00",
        "snippet": "Please send: (1) SSIM ESG integration policy, (2) proxy voting record 2025, (3) SFDR Article 8/9 fund list, (4) carbon footprint comparison for ESG Global Equity vs MSCI World.",
        "customer": "GIC",
    },
    {
        "id": "e_s004",
        "from": "thomas.bradley@osc.ny.gov",
        "to": "sarah.chen@statestreet.com",
        "subject": "NYSCRF — Global Equity Review — Open to Reconsidering",
        "date": (datetime.date.today() - datetime.timedelta(days=30)).isoformat() + "T09:00:00-04:00",
        "snippet": "We're reviewing our passive equity arrangements. Vanguard doesn't offer much on ESG engagement or securities lending. If SSIM can demonstrate total value advantage including lending income, we'd consider re-evaluation.",
        "customer": "New York State Common Retirement Fund",
    },
]

MOCK_DRIVE_DOCS = [
    {
        "id": "sd_001",
        "name": "SSIM Active Quant Equity — OTPP Pitch Deck",
        "category": "pitch_deck",
        "tags": ["active", "quantitative", "otpp", "equity", "factor", "track record"],
        "content": "SSIM Active Quant Equity pitch for OTPP. Includes 5Y track record, factor attribution, 2022 drawdown analysis, fee proposal.",
    },
    {
        "id": "sd_002",
        "name": "SSIM ESG Programme — GIC Pre-read Pack",
        "category": "product",
        "tags": ["esg", "gic", "sfdr", "article9", "carbon", "proxy voting", "sustainable"],
        "content": "ESG pre-read for GIC. Covers SSIM ESG integration policy, SFDR classification, proxy voting statistics, carbon footprint data.",
    },
    {
        "id": "sd_003",
        "name": "Securities Lending Income Analysis — Institutional Client Template",
        "category": "strategy",
        "tags": ["securities lending", "income", "bps", "total cost", "fee comparison", "calpers", "nyscrf"],
        "content": "Template showing securities lending income impact on total cost. SSIM: 1.2 bps gross - 11 bps lending = 0.2 bps net advantage vs Vanguard at 1.0 bps with zero lending.",
    },
    {
        "id": "sd_004",
        "name": "Pension Fund Case Study — Large US Public Pension ($7B Passive Mandate)",
        "category": "case_study",
        "tags": ["pension", "passive", "case study", "us", "global equity", "securities lending"],
        "content": "Case study: Large US public pension fund. $7B MSCI World mandate. Result: tracking error 2.8 bps, securities lending +11 bps annually, ESG implementation within 90 days of inception. Net of fees: +9 bps vs peer average.",
    },
    {
        "id": "sd_005",
        "name": "Sovereign Wealth Fund Case Study — $5B ESG Equity Mandate",
        "category": "case_study",
        "tags": ["sovereign wealth", "swf", "esg", "article9", "sfdr", "case study", "equity"],
        "content": "Case study: European sovereign wealth fund. $5B ESG Global Equity mandate. SFDR Article 9 classification achieved. Carbon footprint: -38% vs MSCI World. Client: strong satisfaction with proxy voting engagement programme.",
    },
    {
        "id": "sd_006",
        "name": "Insurance Company Case Study — Liability Matching Fixed Income",
        "category": "case_study",
        "tags": ["insurance", "liability matching", "fixed income", "long duration", "case study"],
        "content": "Case study: US insurance company. $2B long-duration bond mandate (liability matching). Duration match within 0.05 years. Solvency II compliant. Securities lending on corporate bonds: +3 bps.",
    },
    {
        "id": "sd_007",
        "name": "Endowment Case Study — Multi-Asset ESG Portfolio",
        "category": "case_study",
        "tags": ["endowment", "multi-asset", "esg", "case study", "university"],
        "content": "Case study: US university endowment. $800M multi-asset portfolio combining passive equity, ESG corporate bonds, and cash management. Fossil fuel exclusion implemented. 3Y return: +12.8% vs policy benchmark +12.2%.",
    },
    {
        "id": "sd_008",
        "name": "SSIM Competitive Analysis — BlackRock vs SSIM for Institutional Index",
        "category": "competitive",
        "tags": ["blackrock", "competitive", "comparison", "index", "passive", "fee"],
        "content": "Head-to-head comparison: BlackRock iShares vs SSIM for institutional passive equity. Key differentiator: SSIM lending income (+11 bps) vs BlackRock (+7 bps on similar mandate). SSIM net advantage: ~4 bps despite comparable gross fees.",
    },
]
