"""
Mock data for Daily Briefing Agent — State Street Investment Management.
Simulates Gmail, Google Calendar, and market context responses.
"""

import datetime

_TODAY = datetime.date.today().isoformat()
_TOMORROW = (datetime.date.today() + datetime.timedelta(days=1)).isoformat()

MOCK_CALENDAR_EVENTS = [
    {
        "id": "cal_001",
        "date": _TODAY,
        "title": "Morning Portfolio Review — Global Equity Index Team",
        "start": f"{_TODAY}T08:30:00-04:00",
        "end": f"{_TODAY}T09:00:00-04:00",
        "location": "Conference Room 4A, Boston",
        "description": "Daily review of overnight NAV movements, index replication errors, and corporate actions.",
        "attendees": [
            "sarah.chen@statestreet.com",
            "james.okonkwo@statestreet.com",
            "dev@chenkeamonwang.altostrat.com",
        ],
        "meeting_type": "internal",
        "video_link": "https://meet.google.com/abc-defg-hij",
    },
    {
        "id": "cal_002",
        "date": _TODAY,
        "title": "CalPERS — Q2 2026 Investment Review",
        "start": f"{_TODAY}T10:00:00-04:00",
        "end": f"{_TODAY}T11:30:00-04:00",
        "location": "Zoom",
        "description": "Quarterly review of CalPERS' $8.2B passive equity mandate. Agenda: Q2 performance, ESG screening update, fee discussion for upcoming renewal.",
        "attendees": [
            "michael.torres@calpers.ca.gov",
            "jennifer.wu@calpers.ca.gov",
            "dev@chenkeamonwang.altostrat.com",
            "sarah.chen@statestreet.com",
            "robert.kim@statestreet.com",
        ],
        "meeting_type": "customer",
        "video_link": "https://zoom.us/j/12345678",
        "is_customer_meeting": True,
    },
    {
        "id": "cal_003",
        "date": _TODAY,
        "title": "ESG Integration Working Group",
        "start": f"{_TODAY}T13:00:00-04:00",
        "end": f"{_TODAY}T14:00:00-04:00",
        "location": "Teams",
        "description": "Monthly working group: review of proxy voting decisions, climate data vendors, SFDR Article 8/9 classification review.",
        "attendees": [
            "anna.petrov@statestreet.com",
            "dev@chenkeamonwang.altostrat.com",
            "mark.johnson@statestreet.com",
            "lisa.huang@statestreet.com",
        ],
        "meeting_type": "internal",
        "video_link": "https://teams.microsoft.com/l/meetup-join/mock",
    },
    {
        "id": "cal_004",
        "date": _TODAY,
        "title": "New Mandate Pitch — Ontario Teachers' Pension Plan",
        "start": f"{_TODAY}T15:00:00-04:00",
        "end": f"{_TODAY}T16:30:00-04:00",
        "location": "Toronto Office / Video",
        "description": "Pitch for $2B Active Quantitative Equity mandate. OTPP is evaluating 4 managers. Focus on our systematic approach and factor exposures.",
        "attendees": [
            "david.morrison@otpp.com",
            "francesca.lim@otpp.com",
            "dev@chenkeamonwang.altostrat.com",
            "peter.walsh@statestreet.com",
        ],
        "meeting_type": "customer",
        "video_link": "https://zoom.us/j/87654321",
        "is_customer_meeting": True,
    },
    {
        "id": "cal_005",
        "date": _TODAY,
        "title": "Risk Committee — Weekly Standup",
        "start": f"{_TODAY}T16:30:00-04:00",
        "end": f"{_TODAY}T17:00:00-04:00",
        "location": "Internal",
        "description": "Weekly risk metrics review: tracking error, factor exposures, liquidity, VaR summary across all strategies.",
        "attendees": [
            "dev@chenkeamonwang.altostrat.com",
            "james.okonkwo@statestreet.com",
            "anna.petrov@statestreet.com",
        ],
        "meeting_type": "internal",
        "video_link": "",
    },
    {
        "id": "cal_006",
        "date": _TOMORROW,
        "title": "Singapore GIC — ESG Mandate Scoping Call",
        "start": f"{_TOMORROW}T09:00:00-04:00",
        "end": f"{_TOMORROW}T10:00:00-04:00",
        "location": "Video",
        "description": "Initial scoping for potential $5B ESG Global Equity mandate. GIC is exploring options for their new sustainable allocation.",
        "attendees": [
            "wei.chen@gic.com.sg",
            "dev@chenkeamonwang.altostrat.com",
        ],
        "meeting_type": "customer",
        "is_customer_meeting": True,
        "video_link": "https://meet.google.com/xyz-abc-def",
    },
]

MOCK_EMAILS = [
    {
        "id": "email_001",
        "from": "michael.torres@calpers.ca.gov",
        "to": "dev@chenkeamonwang.altostrat.com",
        "subject": "RE: Q2 2026 Performance Data — Action Required Before Meeting",
        "date": f"{_TODAY}T07:15:00-04:00",
        "snippet": "Could you please confirm the Q2 attribution analysis will be ready before our 10am call today? Also, CFO has asked about the fee schedule for the mandate renewal — please bring updated numbers.",
        "labels": ["UNREAD", "IMPORTANT"],
        "needs_action": True,
        "starred": True,
    },
    {
        "id": "email_002",
        "from": "risk-alerts@statestreet.com",
        "to": "dev@chenkeamonwang.altostrat.com",
        "subject": "ALERT: MSCI World Index Rebalance — 47 Constituent Changes Effective June 2",
        "date": f"{_TODAY}T06:00:00-04:00",
        "snippet": "Automated alert: MSCI World June 2026 rebalance confirmed. 47 additions, 31 deletions. Net flow impact estimated at $2.1B across all passive mandates. Review required by 3pm ET.",
        "labels": ["UNREAD"],
        "needs_action": True,
        "starred": False,
    },
    {
        "id": "email_003",
        "from": "francesca.lim@otpp.com",
        "to": "dev@chenkeamonwang.altostrat.com",
        "subject": "Agenda Confirmation — SSIM Active Quant Pitch Today",
        "date": f"{_TODAY}T08:00:00-04:00",
        "snippet": "Confirming today's 3pm call. Our CIO will join unexpectedly. Please ensure you have slides on: (1) 5-year live track record, (2) factor exposures vs benchmark, (3) drawdown during 2022 selloff, (4) fee structure for $2B mandate.",
        "labels": ["UNREAD"],
        "needs_action": True,
        "starred": False,
    },
    {
        "id": "email_004",
        "from": "compliance@statestreet.com",
        "to": "dev@chenkeamonwang.altostrat.com",
        "subject": "Deadline: SEC Marketing Rule Review — Response Due by EOD Friday",
        "date": f"{_TODAY}T09:30:00-04:00",
        "snippet": "Please review and approve the updated composite performance presentations attached. The SEC Marketing Rule compliance review must be completed before any external distribution. Deadline: Friday COB.",
        "labels": ["UNREAD"],
        "needs_action": True,
        "starred": False,
    },
    {
        "id": "email_005",
        "from": "bloomberg-data@bloomberg.net",
        "to": "dev@chenkeamonwang.altostrat.com",
        "subject": "Morning Market Intelligence — May 16, 2026",
        "date": f"{_TODAY}T05:30:00-04:00",
        "snippet": "Global equities: S&P 500 futures +0.4%. MSCI EM -0.8% on USD strength. Fed minutes today at 2pm ET. 10Y UST at 4.21%. Oil -1.2%. NVDA earnings after close.",
        "labels": ["INBOX"],
        "needs_action": False,
        "starred": False,
    },
    {
        "id": "email_006",
        "from": "anna.petrov@statestreet.com",
        "to": "dev@chenkeamonwang.altostrat.com",
        "subject": "ESG Working Group — Pre-read attached",
        "date": f"{_TODAY}T08:45:00-04:00",
        "snippet": "Sending pre-read for today's 1pm ESG working group. Key items: SFDR reclassification proposal for 3 funds, ISS proxy policy update, and new climate data vendor evaluation summary.",
        "labels": ["INBOX"],
        "needs_action": False,
        "starred": True,
    },
    {
        "id": "email_007",
        "from": "peter.walsh@statestreet.com",
        "to": "dev@chenkeamonwang.altostrat.com",
        "subject": "OTPP CIO joining today — Update strategy",
        "date": f"{_TODAY}T09:00:00-04:00",
        "snippet": "Just got word that OTPP CIO Priya Mehta will join the 3pm call. She's focused on governance and drawdown risk. Adjust opening to lead with our risk management framework before performance.",
        "labels": ["UNREAD", "STARRED"],
        "needs_action": True,
        "starred": True,
    },
    {
        "id": "email_008",
        "from": "wei.chen@gic.com.sg",
        "to": "dev@chenkeamonwang.altostrat.com",
        "subject": "RE: Singapore GIC ESG Mandate — Pre-call Questions",
        "date": f"{_TODAY}T03:00:00-04:00",
        "snippet": "Thank you for setting up tomorrow's call. Before we connect, could you send us: (1) your ESG integration policy, (2) proxy voting record for 2025, (3) Article 8/9 fund list, (4) carbon footprint of SSIM's flagship ESG equity strategy.",
        "labels": ["UNREAD"],
        "needs_action": True,
        "starred": False,
    },
    {
        "id": "email_009",
        "from": "james.okonkwo@statestreet.com",
        "to": "dev@chenkeamonwang.altostrat.com",
        "subject": "Q2 Attribution Analysis Ready",
        "date": f"{_TODAY}T07:45:00-04:00",
        "snippet": "Q2 attribution is ready for CalPERS. Global Equity passive: +12 bps vs benchmark net of fees. Main drag: healthcare sector tilt at rebalance. Document shared in Drive.",
        "labels": ["INBOX"],
        "needs_action": False,
        "starred": False,
    },
    {
        "id": "email_010",
        "from": "david.morrison@otpp.com",
        "to": "dev@chenkeamonwang.altostrat.com",
        "subject": "OTPP RFP — Shortlist Notification",
        "date": (
            datetime.date.today() - datetime.timedelta(days=2)
        ).isoformat() + "T14:00:00-04:00",
        "snippet": "We are pleased to inform you that SSIM has been shortlisted for the Active Quantitative Equity mandate. You are one of 4 managers invited to present. Today's call is your final presentation.",
        "labels": ["INBOX", "STARRED"],
        "needs_action": False,
        "starred": True,
    },
]

MOCK_MARKET_CONTEXT = {
    "date": _TODAY,
    "market_snapshot": {
        "sp500_futures": "+0.4%",
        "msci_world": "+0.2%",
        "msci_em": "-0.8%",
        "us_10y_yield": "4.21%",
        "usd_index": "+0.3%",
        "oil_wti": "-1.2%",
        "gold": "+0.1%",
        "vix": "14.2",
    },
    "ssim_aum_snapshot": {
        "total_aum": "$4.13 trillion",
        "equity_aum": "$2.8 trillion",
        "fixed_income_aum": "$0.9 trillion",
        "cash_aum": "$0.3 trillion",
        "multi_asset_aum": "$0.13 trillion",
        "esg_aum": "$0.6 trillion",
        "aum_change_mtd": "+$8.2B (net new + market appreciation)",
    },
    "key_events_today": [
        "Fed meeting minutes released at 2:00 PM ET — watch for language on rate path",
        "MSCI World rebalance effective date: June 2 — preparation and trade execution required",
        "NVDA earnings after market close — position review needed for tech-heavy mandates",
        "SEC Marketing Rule compliance deadline: Friday COB",
    ],
    "portfolio_alerts": [
        {
            "type": "index_rebalance",
            "severity": "high",
            "message": "MSCI World June rebalance: 47 additions, 31 deletions. Net flow ~$2.1B impact across passive mandates.",
            "action_required": "Coordinate with trading desk on execution schedule",
        },
        {
            "type": "mandate_renewal",
            "severity": "medium",
            "message": "CalPERS mandate renewal due Q3 2026 — fee negotiation in progress",
            "action_required": "Confirm fee proposal with BD team before today's meeting",
        },
        {
            "type": "esg_classification",
            "severity": "medium",
            "message": "3 SSIM funds under SFDR reclassification review (Article 8 → Article 9 upgrade)",
            "action_required": "ESG working group review today at 1pm",
        },
    ],
    "regulatory_reminders": [
        "AIFMD reporting deadline: June 30, 2026",
        "SEC Form ADV annual update: filed",
        "MiFID II transaction reporting: current",
        "SFDR periodic reports: Q2 due July 31",
    ],
    "securities_lending": {
        "utilisation_rate": "67%",
        "revenue_ytd": "$142M",
        "top_earner": "SSIM Global Equity Index (Enhanced Class)",
        "alert": "Recall pending on 3 positions for MSCI rebalance — trading desk notified",
    },
}
